### ISSUE TITLE
`steps.ghd.outputs.sha` does not return short sha

### ISSUE THREAD

**Issue by garciagenrique** [proudust/gh-describe#86]
Hi, 
```yaml
(...)
      - name: Extract metadata for ${{ matrix.containers }}
        id: metadata
        uses: docker/metadata-action@v5.3.0
        with:
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.ghd.outputs.tag }}-${{ steps.ghd.outputs.distance }}-${{ steps.ghd.outputs.sha }}
(...)
```
return `ghcr.io/vre-hub/vre-iam-rucio-sync:v1.0.0-rc.1-17-05d57f74bb467c964fc25756af6c44cd5cd7f161` not `05d57f7` as expected and described on the docs 

https://github.com/vre-hub/vre/actions/runs/7225844181/job/19690127353#step:5:40
